# Generated by Django 4.2.1 on 2023-05-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
                ('tg', models.CharField(max_length=200, unique=True, verbose_name='Телеграмм')),
                ('language', models.CharField(max_length=3, verbose_name='Язык')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('exchange_type', models.CharField(max_length=50, verbose_name='Статус')),
                ('on', models.BooleanField(default=True, verbose_name='Вкл')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('deadline', models.DateTimeField(verbose_name='Срок заказа')),
                ('proof', models.ImageField(upload_to='proof', verbose_name='Подтверждение')),
                ('priority', models.IntegerField(default=3, verbose_name='Приоритет')),
                ('payment_type', models.CharField(max_length=50, verbose_name='Тип оплаты')),
                ('status', models.CharField(default='Не в работе', max_length=50, verbose_name='Статус')),
                ('bundle', models.BooleanField(default=False, verbose_name='Связка')),
                ('comment', models.CharField(max_length=250, verbose_name='Коментарий')),
                ('order_type', models.CharField(max_length=50, verbose_name='Тип заказа')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='manager.clients')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=250, verbose_name='Коментарий')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.exchanges')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='manager.orders')),
            ],
        ),
    ]
