# Generated by Django 4.2.1 on 2023-05-07 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_clients_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Страна')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='emulator',
            field=models.CharField(default=1, max_length=250, verbose_name='Эмулятор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='mail_type',
            field=models.CharField(default=1, max_length=250, verbose_name='Тип почты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='type_of_number',
            field=models.CharField(default=1, max_length=250, verbose_name='Тип номера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='geo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='geos', to='manager.geo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='manager.geo'),
            preserve_default=False,
        ),
    ]
