# Generated by Django 4.2.1 on 2023-05-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_geo_products_emulator_products_mail_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchanges',
            name='on',
        ),
    ]
