# Generated by Django 4.2.1 on 2023-05-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_products_exchange_remove_products_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.exchanges'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='geo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='geos', to='manager.geo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=1, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='resident',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='residents', to='manager.geo'),
            preserve_default=False,
        ),
    ]
