# Generated by Django 4.2.1 on 2023-05-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_products_exchange_products_geo_products_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='emulator',
        ),
    ]
