# Generated by Django 4.2.1 on 2023-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_products_emulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='emulator',
            field=models.CharField(default=1, max_length=250, verbose_name='Эмулятор'),
            preserve_default=False,
        ),
    ]
